on:
  push:
    branches: [master]
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v7
      
      - run: sudo apt-get update
      
      - run: sudo apt-get -y install libcurl4-openssl-dev libmosquitto-dev
      
      - run: cmake .
      
      - run: make -j